name: Java CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push]

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: 'adopt'

      - name: Set up .env
        run: |
          echo TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY }} >> .env
          echo TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET }} >> .env
          echo TWITTER_TOKEN=${{ secrets.TWITTER_TOKEN }} >> .env
          echo TWITTER_TOKEN_SECRET=${{ secrets.TWITTER_TOKEN_SECRET }} >> .env

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: build

      - name: Test and coverage
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: test cucumber jacocoTestReport coverallsJacoco

      - name: Test integration with twitter
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: integrationTest
  tests:
    name: "Run e2e"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Install bashunit"
        run: |
          curl -s https://bashunit.typeddevs.com/install.sh > install.sh
          chmod +x install.sh
          ./install.sh

      - name: "Test"
        run: "./lib/bashunit e2e"
